### ISSUE TITLE
assetClient ledger error

### ISSUE THREAD

**Issue by mbolesta** [AssetMantle/node#4]
Steps to repo:
1. git clone https://github.com/AssetMantle/node.git
2. make install
3. assetClient keys add ledger --ledger --keyring-backend file

I get the following error:
ERROR: ledger nano S: support for ledger devices is not available in this executable

**Comment by mbolesta** [comment]
ended up downloading the binary

**Comment by cryptotech101** [comment]
@mbolesta can you confirm which binary release you downloaded? I'm still getting the same issue as you when you pre-compiled binaries.

**Comment by mbolesta** [comment]
@cryptotech101 when I run the version command it lists out:
```
HEAD-5b2b0dcb37b107b0e0c1eaf9e907aa9f1a1992d9
```

I would have downloaded it around April 20th if that helps. I just tried adding another grant transaction for REStake and it worked.

**Comment by cryptotech101** [comment]
@mbolesta You are legend. Checking out that particular commit worked. Thanks for the help 👍. BTW I have updated my article with the above detail. You can check it out here https://dev.to/_cryptotech101/auto-compound-using-restakeapp-2c59
